# render.yaml
services:
  - type: web
    name: fin-path-insight-fastapi
    env: python
<<<<<<< HEAD
    plan: free
    region: singapore
    runtime: python3
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: chmod +x ./start.sh && ./start.sh
=======
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
>>>>>>> 2e0a894f26bc330c63a124b105795a1ff6f4338e
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: PINECONE_CLOUD
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: PORT
        value: 10000
